"""Convert the Deceptive Opinion Spam corpus to TrustLens training schema.

The source corpus provides gold labels in ``deceptive`` and sentiment polarity.
No review text or class labels are generated by this script.
"""

import argparse
from pathlib import Path

import pandas as pd


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = ROOT / "data" / "deceptive_opinion_spam_source.csv"
DEFAULT_OUTPUT = ROOT / "data" / "deceptive_opinion_spam.csv"


def convert(source: Path, output: Path) -> None:
    frame = pd.read_csv(source)
    required = {"deceptive", "polarity", "text"}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"Source dataset is missing columns: {sorted(missing)}")

    labels = frame["deceptive"].map({"truthful": 0, "deceptive": 1})
    ratings = frame["polarity"].map({"negative": 1.0, "positive": 5.0})
    output_frame = pd.DataFrame(
        {
            "review_text": frame["text"].astype(str).str.strip(),
            "rating": ratings,
            "label": labels,
        }
    ).dropna()

    if output_frame["label"].nunique() != 2 or output_frame["review_text"].nunique() < 100:
        raise ValueError("Source corpus failed label or text-diversity validation.")

    output.parent.mkdir(parents=True, exist_ok=True)
    output_frame.to_csv(output, index=False)
    print(f"Saved {len(output_frame)} real labeled reviews -> {output}")
    print(output_frame["label"].value_counts().sort_index().to_string())


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare Deceptive Opinion Spam corpus")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    convert(args.source, args.output)


if __name__ == "__main__":
    main()
